import { Product, Category, Brand, Color, Size, FilterOptions } from '../models/product.model';

// ==================== CATEGORIES ====================
export const MOCK_CATEGORIES: Category[] = [
    { id: 1, name: 'Giày Nam', status: 1 },
    { id: 2, name: 'Giày Nữ', status: 1 },
    { id: 3, name: 'Giày Trẻ Em', status: 1 },
    { id: 4, name: 'Dép & Sandal', status: 1 },
];

// ==================== BRANDS ====================
export const MOCK_BRANDS: Brand[] = [
    { id: 1, name: 'Nike', status: 1 },
    { id: 2, name: 'Adidas', status: 1 },
    { id: 3, name: 'Jordan', status: 1 },
    { id: 4, name: 'Puma', status: 1 },
    { id: 5, name: 'New Balance', status: 1 },
];

// ==================== COLORS ====================
export const MOCK_COLORS: Color[] = [
    { id: 1, tableColor: '#FFFFFF', name: 'Trắng' },
    { id: 2, tableColor: '#000000', name: 'Đen' },
    { id: 3, tableColor: '#FF0000', name: 'Đỏ' },
    { id: 4, tableColor: '#0066FF', name: 'Xanh Dương' },
    { id: 5, tableColor: '#808080', name: 'Xám' },
    { id: 6, tableColor: '#FFA500', name: 'Cam' },
    { id: 7, tableColor: '#FFD700', name: 'Vàng' },
    { id: 8, tableColor: '#FFC0CB', name: 'Hồng' },
];

// ==================== SIZES ====================
export const MOCK_SIZES: Size[] = [
    { id: 1, bangSize: '36' },
    { id: 2, bangSize: '37' },
    { id: 3, bangSize: '38' },
    { id: 4, bangSize: '39' },
    { id: 5, bangSize: '40' },
    { id: 6, bangSize: '41' },
    { id: 7, bangSize: '42' },
    { id: 8, bangSize: '43' },
    { id: 9, bangSize: '44' },
];

// ==================== FILTER OPTIONS ====================
export const MOCK_FILTER_OPTIONS: FilterOptions = {
    categories: MOCK_CATEGORIES,
    brands: MOCK_BRANDS,
    colors: MOCK_COLORS,
    sizes: MOCK_SIZES,
    priceRange: { min: 1000000, max: 10000000 }
};

// ==================== PRODUCTS ====================
export const MOCK_PRODUCTS: Product[] = [
    {
        id: 1,
        name: "Nike Air Force 1 '07 Mini Jewel",
        image: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/af407d53-37b0-4f36-b709-aba1c8d916fc/AIR+FORCE+1+%2707.png',
        images: [
            'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/af407d53-37b0-4f36-b709-aba1c8d916fc/AIR+FORCE+1+%2707.png',
            'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/0329431c-bfa8-4dfb-9366-4131de5c81de/AIR+FORCE+1+%2707.png',
            'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/2b7e2311-5369-4f7f-85d0-9942a7ebf4f5/AIR+FORCE+1+%2707.png',
            'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/b88b2eb5-2b0e-4ab4-8e4d-0e42d8f99ad5/AIR+FORCE+1+%2707.png'
        ],
        description: 'Thoải mái, bền bỉ và vượt thời gian — mẫ đáng được cải tiến mà không thay đổi quá nhiều.',
        material: 'Da',
        dateAdd: '2026-02-15',
        categoryId: 1,
        brandId: 1,
        category: { id: 1, name: 'Giày Nam' },
        brand: { id: 1, name: 'Nike' },
        variants: [
            { id: 1, productId: 1, colorId: 1, sizeId: 5, price: 2695000, priceSale: undefined, quantity: 50, color: { id: 1, tableColor: '#FFFFFF', name: 'Trắng' }, size: { id: 5, bangSize: '40' } },
            { id: 2, productId: 1, colorId: 2, sizeId: 6, price: 2695000, priceSale: undefined, quantity: 35, color: { id: 2, tableColor: '#000000', name: 'Đen' }, size: { id: 6, bangSize: '41' } },
            { id: 3, productId: 1, colorId: 4, sizeId: 7, price: 2695000, priceSale: undefined, quantity: 20, color: { id: 4, tableColor: '#0066FF', name: 'Xanh Dương' }, size: { id: 7, bangSize: '42' } },
        ],
        minPrice: 2695000,
    },
    {
        id: 2,
        name: 'Nike Air Max 90',
        image: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/fd17b420-b388-4c8a-aaaa-e0a98ddf175f/W+AIR+MAX+90.png',
        images: [
            'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/fd17b420-b388-4c8a-aaaa-e0a98ddf175f/W+AIR+MAX+90.png',
            'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/1ec7df1d-045e-4348-afc7-53e7d23a63f1/W+AIR+MAX+90.png',
            'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/ec7a8f33-cff6-47b2-a429-2882db8a2a53/W+AIR+MAX+90.png'
        ],
        description: 'Đôi giày huyền thoại từ những năm 90 trở lại với thiết kế hiện đại.',
        material: 'Da tổng hợp',
        dateAdd: '2026-02-10',
        categoryId: 1,
        brandId: 1,
        category: { id: 1, name: 'Giày Nam' },
        brand: { id: 1, name: 'Nike' },
        variants: [
            { id: 4, productId: 2, colorId: 1, sizeId: 5, price: 3195000, priceSale: 2795000, quantity: 40, color: { id: 1, tableColor: '#FFFFFF', name: 'Trắng' }, size: { id: 5, bangSize: '40' } },
            { id: 5, productId: 2, colorId: 5, sizeId: 6, price: 3195000, priceSale: 2795000, quantity: 25, color: { id: 5, tableColor: '#808080', name: 'Xám' }, size: { id: 6, bangSize: '41' } },
        ],
        minPrice: 3195000,
        minPriceSale: 2795000,
    },
    {
        id: 3,
        name: 'Adidas Ultraboost Light',
        image: 'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/68f028948f0b4468a4d8af4600f5cbe6_9366/Ultraboost_Light_Running_Shoes_White_HQ6351_01_standard.jpg',
        description: 'Ultraboost Light - đôi giày chạy bộ nhẹ nhất từ trước đến nay.',
        material: 'Primeknit',
        dateAdd: '2026-02-20',
        categoryId: 1,
        brandId: 2,
        category: { id: 1, name: 'Giày Nam' },
        brand: { id: 2, name: 'Adidas' },
        variants: [
            { id: 6, productId: 3, colorId: 1, sizeId: 5, price: 4590000, priceSale: undefined, quantity: 30, color: { id: 1, tableColor: '#FFFFFF', name: 'Trắng' }, size: { id: 5, bangSize: '40' } },
            { id: 7, productId: 3, colorId: 2, sizeId: 7, price: 4590000, priceSale: undefined, quantity: 20, color: { id: 2, tableColor: '#000000', name: 'Đen' }, size: { id: 7, bangSize: '42' } },
        ],
        minPrice: 4590000,
    },
    {
        id: 4,
        name: 'Jordan 1 Retro High OG',
        image: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/2bff48f0-b136-4a,da-aa2f-45c30cbca52b/AIR+JORDAN+1+RETRO+HIGH+OG.png',
        description: 'Phong cách cổ điển của Michael Jordan trở lại.',
        material: 'Da thật',
        dateAdd: '2026-01-25',
        categoryId: 1,
        brandId: 3,
        category: { id: 1, name: 'Giày Nam' },
        brand: { id: 3, name: 'Jordan' },
        variants: [
            { id: 8, productId: 4, colorId: 3, sizeId: 6, price: 4295000, priceSale: undefined, quantity: 15, color: { id: 3, tableColor: '#FF0000', name: 'Đỏ' }, size: { id: 6, bangSize: '41' } },
            { id: 9, productId: 4, colorId: 2, sizeId: 7, price: 4295000, priceSale: undefined, quantity: 18, color: { id: 2, tableColor: '#000000', name: 'Đen' }, size: { id: 7, bangSize: '42' } },
        ],
        minPrice: 4295000,
    },
    {
        id: 5,
        name: 'Nike Dunk Low Retro',
        image: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/bcdaf1d4-6e0b-46a0-8ad2-5eb4e2332a0e/NIKE+DUNK+LOW+RETRO.png',
        description: 'Phong cách đường phố huyền thoại.',
        material: 'Da',
        dateAdd: '2026-02-25',
        categoryId: 1,
        brandId: 1,
        category: { id: 1, name: 'Giày Nam' },
        brand: { id: 1, name: 'Nike' },
        variants: [
            { id: 10, productId: 5, colorId: 1, sizeId: 5, price: 2695000, priceSale: undefined, quantity: 60, color: { id: 1, tableColor: '#FFFFFF', name: 'Trắng' }, size: { id: 5, bangSize: '40' } },
            { id: 11, productId: 5, colorId: 2, sizeId: 6, price: 2695000, priceSale: undefined, quantity: 45, color: { id: 2, tableColor: '#000000', name: 'Đen' }, size: { id: 6, bangSize: '41' } },
        ],
        minPrice: 2695000,
    },
    {
        id: 6,
        name: 'Adidas Grand Court Cloudfoam',
        image: 'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/3621652c72034e30a75e4b8b20f93658_9366/Grand_Court_Cloudfoam_Comfort_Shoes_White_GW9196_01_standard.jpg',
        description: 'Phong cách tennis cổ điển với đệm Cloudfoam.',
        material: 'Da tổng hợp',
        dateAdd: '2026-01-20',
        categoryId: 1,
        brandId: 2,
        category: { id: 1, name: 'Giày Nam' },
        brand: { id: 2, name: 'Adidas' },
        variants: [
            { id: 12, productId: 6, colorId: 1, sizeId: 5, price: 2190000, priceSale: 1790000, quantity: 70, color: { id: 1, tableColor: '#FFFFFF', name: 'Trắng' }, size: { id: 5, bangSize: '40' } },
            { id: 13, productId: 6, colorId: 7, sizeId: 6, price: 2190000, priceSale: 1790000, quantity: 50, color: { id: 7, tableColor: '#FFD700', name: 'Vàng' }, size: { id: 6, bangSize: '41' } },
        ],
        minPrice: 2190000,
        minPriceSale: 1790000,
    },
    {
        id: 7,
        name: 'Nike Air Max 97',
        image: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/e4d34e11-dba8-446c-8e10-a6e65f9d0ffd/AIR+MAX+97.png',
        description: 'Thiết kế gợn sóng đặc trưng, lấy cảm hứng từ đường ray tàu Shinkansen.',
        material: 'Da & vải',
        dateAdd: '2026-03-01',
        categoryId: 1,
        brandId: 1,
        category: { id: 1, name: 'Giày Nam' },
        brand: { id: 1, name: 'Nike' },
        variants: [
            { id: 14, productId: 7, colorId: 5, sizeId: 5, price: 4295000, priceSale: 3595000, quantity: 25, color: { id: 5, tableColor: '#808080', name: 'Xám' }, size: { id: 5, bangSize: '40' } },
        ],
        minPrice: 4295000,
        minPriceSale: 3595000,
    },
    {
        id: 8,
        name: 'Puma RS-X Reinvention',
        image: 'https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_750,h_750/global/369579/16/sv01/fnd/PNA/fmt/png/RS-X-Reinvention-Sneakers',
        description: 'Phong cách retro-future, đệm RS tối ưu.',
        material: 'Vải & da tổng hợp',
        dateAdd: '2026-02-05',
        categoryId: 1,
        brandId: 4,
        category: { id: 1, name: 'Giày Nam' },
        brand: { id: 4, name: 'Puma' },
        variants: [
            { id: 15, productId: 8, colorId: 1, sizeId: 5, price: 2990000, priceSale: undefined, quantity: 35, color: { id: 1, tableColor: '#FFFFFF', name: 'Trắng' }, size: { id: 5, bangSize: '40' } },
            { id: 16, productId: 8, colorId: 6, sizeId: 7, price: 2990000, priceSale: undefined, quantity: 20, color: { id: 6, tableColor: '#FFA500', name: 'Cam' }, size: { id: 7, bangSize: '42' } },
        ],
        minPrice: 2990000,
    },
    {
        id: 9,
        name: 'New Balance 574',
        image: 'https://nb.scene7.com/is/image/NB/ml574evg_nb_02_i?$pdpflexf2$&qlt=80&fmt=webp&wid=880&hei=880',
        description: 'Biểu tượng phong cách classic của New Balance.',
        material: 'Da lộn & vải',
        dateAdd: '2026-01-30',
        categoryId: 1,
        brandId: 5,
        category: { id: 1, name: 'Giày Nam' },
        brand: { id: 5, name: 'New Balance' },
        variants: [
            { id: 17, productId: 9, colorId: 5, sizeId: 5, price: 2490000, priceSale: undefined, quantity: 40, color: { id: 5, tableColor: '#808080', name: 'Xám' }, size: { id: 5, bangSize: '40' } },
            { id: 18, productId: 9, colorId: 4, sizeId: 6, price: 2490000, priceSale: undefined, quantity: 30, color: { id: 4, tableColor: '#0066FF', name: 'Xanh Dương' }, size: { id: 6, bangSize: '41' } },
        ],
        minPrice: 2490000,
    },
    {
        id: 10,
        name: "Nike Air Force 1 '07 LV8",
        image: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/7a5968a9-79da-4ea6-8fac-0c2a0617e8ed/AIR+FORCE+1+%2707+LV8.png',
        description: 'Phiên bản nâng cấp với chi tiết tinh xảo.',
        material: 'Da',
        dateAdd: '2026-03-05',
        categoryId: 1,
        brandId: 1,
        category: { id: 1, name: 'Giày Nam' },
        brand: { id: 1, name: 'Nike' },
        variants: [
            { id: 19, productId: 10, colorId: 1, sizeId: 5, price: 3195000, priceSale: undefined, quantity: 28, color: { id: 1, tableColor: '#FFFFFF', name: 'Trắng' }, size: { id: 5, bangSize: '40' } },
        ],
        minPrice: 3195000,
    },
    {
        id: 11,
        name: 'Nike Air Zoom Pegasus 41',
        image: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/51565586-3a48-4397-8b0e-68c87528d304/AIR+ZOOM+PEGASUS+41.png',
        description: 'Đôi giày chạy bộ đáng tin cậy nhất.',
        material: 'Vải mesh',
        dateAdd: '2026-02-28',
        categoryId: 2,
        brandId: 1,
        category: { id: 2, name: 'Giày Nữ' },
        brand: { id: 1, name: 'Nike' },
        variants: [
            { id: 20, productId: 11, colorId: 8, sizeId: 2, price: 3590000, priceSale: undefined, quantity: 45, color: { id: 8, tableColor: '#FFC0CB', name: 'Hồng' }, size: { id: 2, bangSize: '37' } },
            { id: 21, productId: 11, colorId: 1, sizeId: 3, price: 3590000, priceSale: undefined, quantity: 35, color: { id: 1, tableColor: '#FFFFFF', name: 'Trắng' }, size: { id: 3, bangSize: '38' } },
        ],
        minPrice: 3590000,
    },
    {
        id: 12,
        name: 'Adidas Samba OG',
        image: 'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/19f2e413d07b4ab48a8aaf6a01417e51_9366/Samba_OG_Shoes_White_B75806_01_00_standard.jpg',
        description: 'Phong cách sân cỏ trong nhà trở thành biểu tượng đường phố.',
        material: 'Da',
        dateAdd: '2026-03-02',
        categoryId: 2,
        brandId: 2,
        category: { id: 2, name: 'Giày Nữ' },
        brand: { id: 2, name: 'Adidas' },
        variants: [
            { id: 22, productId: 12, colorId: 1, sizeId: 2, price: 2790000, priceSale: undefined, quantity: 55, color: { id: 1, tableColor: '#FFFFFF', name: 'Trắng' }, size: { id: 2, bangSize: '37' } },
            { id: 23, productId: 12, colorId: 2, sizeId: 3, price: 2790000, priceSale: undefined, quantity: 40, color: { id: 2, tableColor: '#000000', name: 'Đen' }, size: { id: 3, bangSize: '38' } },
        ],
        minPrice: 2790000,
    },
    {
        id: 13,
        name: 'Nike Blazer Mid 77',
        image: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/fb7eda3c-5ac8-4d05-a18f-1c2c5e82e36e/BLAZER+MID+%2777+VNTG.png',
        description: 'Phong cách vintage bóng rổ cổ điển.',
        material: 'Da & vải',
        dateAdd: '2026-01-15',
        categoryId: 2,
        brandId: 1,
        category: { id: 2, name: 'Giày Nữ' },
        brand: { id: 1, name: 'Nike' },
        variants: [
            { id: 24, productId: 13, colorId: 1, sizeId: 2, price: 2590000, priceSale: 2190000, quantity: 30, color: { id: 1, tableColor: '#FFFFFF', name: 'Trắng' }, size: { id: 2, bangSize: '37' } },
        ],
        minPrice: 2590000,
        minPriceSale: 2190000,
    },
    {
        id: 14,
        name: 'Jordan 1 Low SE',
        image: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/c2fc7f40-0721-453d-9e0a-c51e65af0e17/W+AIR+JORDAN+1+LOW+SE.png',
        description: 'Phiên bản Low cổ thấp, phong cách năng động.',
        material: 'Da',
        dateAdd: '2026-02-18',
        categoryId: 2,
        brandId: 3,
        category: { id: 2, name: 'Giày Nữ' },
        brand: { id: 3, name: 'Jordan' },
        variants: [
            { id: 25, productId: 14, colorId: 8, sizeId: 2, price: 3290000, priceSale: undefined, quantity: 22, color: { id: 8, tableColor: '#FFC0CB', name: 'Hồng' }, size: { id: 2, bangSize: '37' } },
            { id: 26, productId: 14, colorId: 1, sizeId: 3, price: 3290000, priceSale: undefined, quantity: 18, color: { id: 1, tableColor: '#FFFFFF', name: 'Trắng' }, size: { id: 3, bangSize: '38' } },
        ],
        minPrice: 3290000,
    },
    {
        id: 15,
        name: 'Adidas Stan Smith',
        image: 'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/78fa5f4a6e4d4eb6a818a8bf01187db2_9366/Stan_Smith_Shoes_White_FX5502_01_standard.jpg',
        description: 'Biểu tượng phong cách tối giản.',
        material: 'Da',
        dateAdd: '2026-02-08',
        categoryId: 2,
        brandId: 2,
        category: { id: 2, name: 'Giày Nữ' },
        brand: { id: 2, name: 'Adidas' },
        variants: [
            { id: 27, productId: 15, colorId: 1, sizeId: 2, price: 2390000, priceSale: undefined, quantity: 80, color: { id: 1, tableColor: '#FFFFFF', name: 'Trắng' }, size: { id: 2, bangSize: '37' } },
        ],
        minPrice: 2390000,
    },
    {
        id: 16,
        name: 'Nike Revolution 7',
        image: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/d0e9e808-f9f0-4e51-95c3-68ca0b6a1e3d/REVOLUTION+7.png',
        description: 'Giày chạy bộ nhẹ nhàng cho mọi cung đường.',
        material: 'Vải mesh',
        dateAdd: '2026-01-10',
        categoryId: 3,
        brandId: 1,
        category: { id: 3, name: 'Giày Trẻ Em' },
        brand: { id: 1, name: 'Nike' },
        variants: [
            { id: 28, productId: 16, colorId: 4, sizeId: 1, price: 1590000, priceSale: undefined, quantity: 50, color: { id: 4, tableColor: '#0066FF', name: 'Xanh Dương' }, size: { id: 1, bangSize: '36' } },
            { id: 29, productId: 16, colorId: 3, sizeId: 2, price: 1590000, priceSale: undefined, quantity: 40, color: { id: 3, tableColor: '#FF0000', name: 'Đỏ' }, size: { id: 2, bangSize: '37' } },
        ],
        minPrice: 1590000,
    },
    {
        id: 17,
        name: 'Adidas Superstar',
        image: 'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/5c3c1e1fdaef4e76a9d2af6a01417aec_9366/Superstar_Shoes_White_EG4958_01_standard.jpg',
        description: 'Shell-toe huyền thoại từ năm 1969.',
        material: 'Da',
        dateAdd: '2026-03-03',
        categoryId: 1,
        brandId: 2,
        category: { id: 1, name: 'Giày Nam' },
        brand: { id: 2, name: 'Adidas' },
        variants: [
            { id: 30, productId: 17, colorId: 1, sizeId: 5, price: 2390000, priceSale: undefined, quantity: 65, color: { id: 1, tableColor: '#FFFFFF', name: 'Trắng' }, size: { id: 5, bangSize: '40' } },
            { id: 31, productId: 17, colorId: 2, sizeId: 6, price: 2390000, priceSale: undefined, quantity: 55, color: { id: 2, tableColor: '#000000', name: 'Đen' }, size: { id: 6, bangSize: '41' } },
        ],
        minPrice: 2390000,
    },
    {
        id: 18,
        name: 'New Balance 530',
        image: 'https://nb.scene7.com/is/image/NB/mr530sg_nb_02_i?$pdpflexf2$&qlt=80&fmt=webp&wid=880&hei=880',
        description: 'Phong cách retro-running đậm chất thập niên 90.',
        material: 'Da tổng hợp & mesh',
        dateAdd: '2026-02-22',
        categoryId: 2,
        brandId: 5,
        category: { id: 2, name: 'Giày Nữ' },
        brand: { id: 5, name: 'New Balance' },
        variants: [
            { id: 32, productId: 18, colorId: 1, sizeId: 2, price: 2790000, priceSale: 2390000, quantity: 38, color: { id: 1, tableColor: '#FFFFFF', name: 'Trắng' }, size: { id: 2, bangSize: '37' } },
        ],
        minPrice: 2790000,
        minPriceSale: 2390000,
    },
    {
        id: 19,
        name: 'Puma Suede Classic XXI',
        image: 'https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_750,h_750/global/374915/01/sv01/fnd/PNA/fmt/png/Suede-Classic-XXI-Sneakers',
        description: 'Biểu tượng streetwear từ Puma.',
        material: 'Da lộn',
        dateAdd: '2026-01-28',
        categoryId: 1,
        brandId: 4,
        category: { id: 1, name: 'Giày Nam' },
        brand: { id: 4, name: 'Puma' },
        variants: [
            { id: 33, productId: 19, colorId: 2, sizeId: 5, price: 1990000, priceSale: undefined, quantity: 42, color: { id: 2, tableColor: '#000000', name: 'Đen' }, size: { id: 5, bangSize: '40' } },
            { id: 34, productId: 19, colorId: 3, sizeId: 6, price: 1990000, priceSale: undefined, quantity: 35, color: { id: 3, tableColor: '#FF0000', name: 'Đỏ' }, size: { id: 6, bangSize: '41' } },
        ],
        minPrice: 1990000,
    },
    {
        id: 20,
        name: 'Nike Air VaporMax Plus',
        image: 'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/e6e25f6a-6a3a-4a6f-be72-7e2905d5cc0d/AIR+VAPORMAX+PLUS.png',
        description: 'Sự kết hợp hoàn hảo giữa VaporMax và Air Max Plus.',
        material: 'Vải tổng hợp',
        dateAdd: '2026-03-06',
        categoryId: 1,
        brandId: 1,
        category: { id: 1, name: 'Giày Nam' },
        brand: { id: 1, name: 'Nike' },
        variants: [
            { id: 35, productId: 20, colorId: 2, sizeId: 5, price: 5590000, priceSale: undefined, quantity: 12, color: { id: 2, tableColor: '#000000', name: 'Đen' }, size: { id: 5, bangSize: '40' } },
            { id: 36, productId: 20, colorId: 6, sizeId: 7, price: 5590000, priceSale: undefined, quantity: 8, color: { id: 6, tableColor: '#FFA500', name: 'Cam' }, size: { id: 7, bangSize: '42' } },
        ],
        minPrice: 5590000,
    },
];
